.SILENT all-patrat:
all-patrat:
	python3 -m nuitka --follow-import-to=charmander patrat.py
	echo [CC] patrat
	python3 -m nuitka --follow-import-to=patrat --follow-import-to=termcolor patratgit.py
	echo [CC] patratgit
	